server:
  port: 8040
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /
  #  session:
  #    cookie:
  #      http-only: true # Also configured in configuration file
  #      secure: true # Also configured in configuration file


spring:
  application:
    name: sample

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
      file-size-threshold: 2KB

  mvc:
    locale: en_US
    locale-resolver: accept_header #fixed
    view:
      prefix: WEB-INF/views/
      suffix: .jsp
    #throw-exception-if-no-handler-found: false

  resources:
    static-locations: classpath:/static/

  messages:
    basename: labels,validation_messages

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sample
    username: sample
    password: sample

  #Set the SQL Dialect to “default” in your labels.properties to let Spring autodetect the different SQL Dialects of each datasource
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

# LOGGING ================================================================================
logging:
  pattern:
    console:  "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36}:%L : %msg%n"
  level:
    com.ss.sample: INFO
    org.hibernate: INFO

management:
  endpoint:
    health:
      enabled: true
      roles: ["ADMIN", "SUPER"]
      show-details: when_authorized
    httptrace:
      enabled: true
  endpoints:
    web:
      base-path: /application
      exposure:
#        include: ["health", "info", "beans", "env", "loggers","metrics"]
        include: "*"
        exclude: loggers

info:
  app:
    name: Sample Project
    java:
      version: 8
    type: Spring Boot

jdoodle:
  client-id: 19e80d4d72411eac1fb3d28ad81b85ea
  client-secret: ef1048f1c6124e1d800b2e3bdbc82b6e0d91b24d5ac2deef096d0ff2631267eb
  host: https://api.jdoodle.com/v1/execute